강사님: 류정원\
이메일: ryuzy@naver.com

# 1. Numpy 란?

수학, 과학 계산용 패키지

성능 : 파이썬의 리스트보다 빠름

메모리 사이즈 : 파이썬의 리스트보다 적은 메모리를 사용

빌트인 함수 : 선형대수, 통계관련 여러 함수들을 내장

In [ ]:
# !pip install numpy  #numpy 설치
import numpy

In [ ]:
numpy

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [ ]:
#별칭(alias) 지정
import numpy as np

In [ ]:
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

## 1-1. array(배열)
여러 값드의 그룹

In [ ]:
arr = np.array([1, 2, 3, 4])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
type(arr) #numpy.ndarray = n dimention array

numpy.ndarray

In [ ]:
list1 = [1, 2, 3, 4]
list2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(list1)
print(list2)

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]


In [ ]:
# 리스트로부터 ndarray 생성 방법
arr1 = np.array(list1)
arr2 = np.array(list2)

In [ ]:
print(type(arr1))
print(type(arr2))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [ ]:
arr1.shape  #차원

(4,)

In [ ]:
arr2.shape

(2, 4)

## 1-2. array에서의 data 타입

array에서는 list와는 다르게 1개의 단일 데이터 타입만 허용

In [ ]:
list = [1, 3, 14, '★', '1234']

In [ ]:
list

[1, 3, 14, '★', '1234']

In [ ]:
list[2]

14

In [ ]:
arr = np.array([1, 2, 3, 4])

In [ ]:
arr

array([1, 2, 3, 4])

In [ ]:
arr = np.array([1, 2, 3, 3.14])

In [ ]:
# int와 float 타입이 같이 존재하는 경우 float 타입으로 저장
arr

array([1.  , 2.  , 3.  , 3.14])

In [ ]:
# int와 float 타입이 같이 존재하는 경우 dtype을 int로 설정
arr = np.array([1, 2, 3, 3.14], dtype=int)

In [ ]:
arr

array([1, 2, 3, 3])

In [ ]:
# int와 str 타입이 같이 존재하는 경우
arr = np.array([1, 3.14, '😉', '1234']) #이모티콘 : 윈도우키 + .

In [ ]:
arr

array(['1', '3.14', '😉', '1234'], dtype='<U32')

In [ ]:
arr[0] + arr[1]

'13.14'

In [ ]:
# int와 str 타입이 같이 존재하는 경우, dtype을 int로 설정
arr = np.array([1, 3.14, '😉', '1234'], dtype=int) #ValueError: invalid literal for int() with base 10: '😉'

ValueError: ignored

In [ ]:
arr = np.array([1, 3.14, '1234'], dtype = int)

In [ ]:
arr

array([   1,    3, 1234])

## 1-3. 슬라이싱(slicing)

배열의 부분 선택

In [ ]:
arr = np.array(['👌', '😘', '🤣', '😜', '👏'])
arr.shape

(5,)

In [ ]:
# index 지정하여 색인
print(arr[0])
print(arr[4])
print(arr[-1])

👌
👏
👏


In [ ]:
# 슬라이싱
print(arr[0:3])
print(arr[2:])
print(arr[:2])

['👌' '😘' '🤣']
['🤣' '😜' '👏']
['👌' '😘']


In [ ]:
# 2차원 array
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [ ]:
arr2d.shape

(3, 4)

In [ ]:
arr2d[0,2]

3

In [ ]:
arr2d[2,1]

10

In [ ]:
# 0 행을 모두 가져오기
print(arr2d[0])
print(arr2d[0,])
print(arr2d[0,:]) #원칙

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [ ]:
# 1열 모두 가져오기
print(arr2d[:, 1])

[ 2  6 10]


In [ ]:
arr2d[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
arr2d[:2, 2:]

array([[3, 4],
       [7, 8]])

## 1-4. Fancy 인덱싱

범위가 아닌 특정 index의 집합의 값을 선택하여 추출하고 싶을 때 활용

In [ ]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

In [ ]:
idx = [1, 3, 5]  #추출하고 싶은 인덱스를 괄호로 묶어 저장

In [ ]:
arr[idx]

array([23,  7, 65])

In [ ]:
# 2차원 array
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [ ]:
arr2d[[0,1],:]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## 1-5. Boolean 인덱싱

조건 필터링을 통하여 Boolean 값을 이용한 색인

In [ ]:
arr = np.array(['👌', '😘', '🤣', '😜', '👏'])

In [ ]:
myValue = [True, False, True, False, True]

In [ ]:
arr[myValue]

array(['👌', '🤣', '👏'], dtype='<U1')

In [ ]:
myValue = [True, False, True]

In [ ]:
arr[myValue]  #IndexError: boolean index did not match indexed array along dimension 0; dimension is 5 but corresponding boolean dimension is 3

IndexError: ignored

In [ ]:
# 2차원 array
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [ ]:
arr2d > 3

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
arr2d[arr2d>3]  #차원이 아닌 결과값만 나옴

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr2d[arr2d<5]

array([1, 2, 3, 4])

# 2. Matrix(행렬)

## 2-1. Matrix

행(row) + 열(column)

데이터분석 및 기계학습에서는 행렬을 제외하고 연산할 수 없음

덧셈
- shape가 같아야 함
- 같은 position끼리 연산

뺄셈
- shape가 같아야 함
- 같은 position끼리 연산

곱셈
- 맞닿는 shape가 같아야 함

In [ ]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [ ]:
a+b

array([[4, 6, 8],
       [3, 5, 7]])

In [ ]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

b = np.array([[3, 4],
              [1, 2]])

In [ ]:
a+b #ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

ValueError: ignored

In [ ]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [ ]:
a-b

array([[-2, -2, -2],
       [ 1,  1,  1]])

In [ ]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

b = np.array([[3, 4],
              [1, 2]])

In [ ]:
a-b   #ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

ValueError: ignored

In [ ]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])

b = np.array([[3, 4, 5],
              [1, 2, 3]])

In [ ]:
a*b

array([[ 3,  8, 15],
       [ 2,  6, 12]])

In [ ]:
a = np.array([[1, 2, 3],
              [1, 2, 3],
              [2, 3, 4]])

b = np.array([[1, 2],
              [3, 4],
              [5, 6]])

In [ ]:
a.shape, b.shape

((3, 3), (3, 2))

In [ ]:
np.dot(a,b)

array([[22, 28],
       [22, 28],
       [31, 40]])

## 2-2. arange

순차적인 값을 생성할 때 사용

In [ ]:
arr = np.arange(1,11)  # 1부터 11미만

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr = np.arange(start=1, stop=11)

In [ ]:
arr = np.arange(1,11,2)

In [ ]:
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = np.arange(start=1, stop=11, step=2) #넘파이 함수

In [ ]:
arr

array([1, 3, 5, 7, 9])

In [ ]:
arr = range(1,11) #파이썬 표준함수
arr

range(1, 11)

In [ ]:
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
arr = np.arange(1,11)
for i in arr:
  print(i)

1
2
3
4
5
6
7
8
9
10


## 2-3. 정렬(sort)

In [ ]:
arr = np.array([1, 10, 5, 8, 2, 4, 3, 6, 8, 7, 9])

In [ ]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [ ]:
np.sort(arr)  #기본적으로 오름차순 정렬

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [ ]:
np.sort(arr)[::-1]  #내림차순 정렬

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
arr #값이 유지되지 않기 때문에 변수에 저장해야 함

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [ ]:
result = np.sort(arr)

In [ ]:
result

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [ ]:
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [ ]:
# n차원 정렬
arr2d = np.array([[11, 10, 12, 9],
                  [3, 1, 4, 2],
                  [5, 6, 7, 8]])

In [ ]:
arr2d.shape

(3, 4)

In [ ]:
arr2d

array([[11, 10, 12,  9],
       [ 3,  1,  4,  2],
       [ 5,  6,  7,  8]])

In [ ]:
# 행 정렬
np.sort(arr2d, axis=0)

array([[ 3,  1,  4,  2],
       [ 5,  6,  7,  8],
       [11, 10, 12,  9]])

In [ ]:
# 열 정렬
np.sort(arr2d, axis=1)

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [ ]:
# argsort : index를 반환
arr2dTest = np.array([[5, 6, 7, 8],
                      [4, 3, 2, 1],
                      [10, 9, 12, 11]])

In [ ]:
np.argsort(arr2dTest, axis=0)

array([[1, 1, 1, 1],
       [0, 0, 0, 0],
       [2, 2, 2, 2]])

In [ ]:
np.argsort(arr2dTest, axis=1)

array([[0, 1, 2, 3],
       [3, 2, 1, 0],
       [1, 0, 3, 2]])

In [ ]:
arr2d = np.array([[11, 10, 12, 9],
                  [3, 1, 4, 2],
                  [5, 6, 7, 8]])

In [ ]:
np.argsort(arr2d, axis=0) #결과 이상함

array([[1, 1, 1, 1],
       [2, 2, 2, 2],
       [0, 0, 0, 0]])

In [ ]:
np.argsort(arr2d, axis=1) #결과 이상함

array([[3, 1, 0, 2],
       [1, 3, 0, 2],
       [0, 1, 2, 3]])

sort 된 후

[1,2,3,4]\
[5,6,7,8]\
[9,10,11,12]

이때 해당 숫자의 원래 행렬의 자리수를 출력

# 3. 숫자의 연산(단일)

In [ ]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 3, 3],
              [3, 3, 3]])

In [ ]:
a + b

array([[4, 5, 6],
       [5, 6, 7]])

In [ ]:
a+3

array([[4, 5, 6],
       [5, 6, 7]])

In [ ]:
a-3

array([[-2, -1,  0],
       [-1,  0,  1]])

In [ ]:
a*3

array([[ 3,  6,  9],
       [ 6,  9, 12]])

In [ ]:
a/3

array([[0.33333333, 0.66666667, 1.        ],
       [0.66666667, 1.        , 1.33333333]])